sudo: required

services:
  - docker

language: java

jdk:
  - openjdk8

after_success:
  - if [ "$TRAVIS_BRANCH" == "master" ]; then
    docker-compose build;
    docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
    docker push mixomat/cvmaker-api:latest;
    fi
